AWSTemplateFormatVersion: '2010-09-09'

Description: Simple Student Management Infrastructure

Resources:

  StudentEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0bf1982bfc7bbc490
      Tags:
        - Key: Name
          Value: StudentManagementServer
